---
volumes:
  scriberr-data: {}
  db-data: {}

services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr:${SCRIBERR_VERSION:-main}
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/scriberr
      OLLAMA_BASE_URL: http://ollama:11434
      AI_MODEL: ${SCRIBERR_MODEL:-llama3.2:latest}
      HF_TOKEN: ${HF_TOKEN:-}
      SCRIBERR_USERNAME: admin
      SCRIBERR_PASSWORD: ${SCRIBERR_PASSWORD:-password}
    ports:
      - 3333:8080
    volumes:
      - scriberr-data:/scriberr
    env_file:
      - .secrets
    depends_on:
      - db
      - ollama

  ollama:
    image: ollama/ollama
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scriberr
    volumes:
      - db-data:/var/lib/postgresql/data
